package com.example.discriminant.controllers;


import com.example.discriminant.Equation;
import com.example.discriminant.repos.EqRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private EqRepo eqRepo;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewEquation (@RequestParam Double a
            , @RequestParam Double b, @RequestParam Double c) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Equation equation = new Equation();
        equation.setA(a);
        equation.setB(b);
        equation.setC(c);
        equation.calculateRootsOfEquation();
        eqRepo.save(equation);
        return "equation saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Equation> getAllUsers() {
        // This returns a JSON or XML with the users
        return eqRepo.findAll();
    }
}
